-- Weather Temperature Prediction --

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor, VotingRegressor
import joblib

# Load the dataset (CSV file) into a pandas DataFrame and Display the first 5 rows of the dataset

In [4]:
data = pd.read_csv("weather_500.csv")
data.head()

,Day,Humidity (%),Pressure (hPa),Wind Speed (km/h),Rainfall (mm),Sunlight (hours),Temperature (°C)
0,1,88,1008,17,8.4,6.6,32.5
1,2,78,1007,19,49.6,6.9,32.3
2,3,64,1014,8,11.6,9.5,35.6
3,4,57,1009,17,47.1,9.2,34.4
4,5,70,1009,28,32.5,11.9,34.5

# Prints all the data Column's Name

In [5]:
print(data.columns)

Index(['Day', 'Humidity (%)', 'Pressure (hPa)', 'Wind Speed (km/h)',
       'Rainfall (mm)', 'Sunlight (hours)', 'Temperature (°C)'],
      dtype='str')

# Seperate Features and Label

In [6]:
X = data[['Day', 'Humidity (%)', 'Pressure (hPa)', 'Wind Speed (km/h)', 'Rainfall (mm)', 'Sunlight (hours)']]
y = data["Temperature (°C)"]

# Display only the features

In [7]:
X

,Day,Humidity (%),Pressure (hPa),Wind Speed (km/h),Rainfall (mm),Sunlight (hours)
0,1,88,1008,17,8.4,6.6
1,2,78,1007,19,49.6,6.9
2,3,64,1014,8,11.6,9.5
3,4,57,1009,17,47.1,9.2
4,5,70,1009,28,32.5,11.9
...,...,...,...,...,...,...
495,496,61,1015,18,29.7,7.2
496,497,58,1014,28,24.8,11.2
497,498,56,1005,15,49.4,7.8
498,499,77,1010,17,6.8,7.5
499,500,63,1010,6,34.8,3.9

# Display only y the Label

In [8]:
y

0      32.5
1      32.3
2      35.6
3      34.4
4      34.5
       ...
495    32.9
496    37.0
497    34.5
498    31.5
499    30.8
Name: Temperature (°C), Length: 500, dtype: float64

# Split the dataset into training and testing sets
# 80% for training, 20% for testing

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
log_reg = LinearRegression()
log_reg.fit(X_train, y_train)
log_pred = log_reg.predict(X_test)
log_acc = r2_score(y_test, log_pred)
print(f"Linear Regression R² Score: {log_acc:.4f}")

Linear Regression R² Score: 0.8762

In [12]:
grad_model = GradientBoostingRegressor()
grad_model.fit(X_train, y_train)
grad_pred = grad_model.predict(X_test)
grad_acc = r2_score(y_test, grad_pred)
print(f"Gradient Boosting R² Score: {grad_acc:.4f}")

Gradient Boosting R² Score: 0.8422

In [13]:
forest_model = RandomForestRegressor()
forest_model.fit(X_train, y_train)
forest_pred = forest_model.predict(X_test)
forest_acc = r2_score(y_test, forest_pred)
print(f"Random Forest R² Score: {forest_acc:.4f}")

Random Forest R² Score: 0.8265

In [14]:
ensemble_model = VotingRegressor(estimators=[
    ('lr', log_reg), 
    ('gb', grad_model), 
    ('rf', forest_model)])
ensemble_model.fit(X_train, y_train)
ensemble_pred = ensemble_model.predict(X_test)
ensemble_acc = r2_score(y_test, ensemble_pred)
print(f"Ensemble R² Score: {ensemble_acc:.4f}")

Ensemble R² Score: 0.8566

# Saves all your trained model: So you can reuse it later without retraining

In [15]:
import joblib
joblib.dump(log_reg, "temperature_predictor_lr_model.pkl")
joblib.dump(grad_model, "temperature_predictor_gb_model.pkl")
joblib.dump(forest_model, "temperature_predictor_rf_model.pkl")
joblib.dump(ensemble_model, "temperature_predictor_ensemble_model.pkl")

['temperature_predictor_ensemble_model.pkl']